#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "PCB_structure.h"

//generation of random integers
int identifier()
{
	int id;
	id = rand();
	return id;
}

clock_t start, end;//clock variables

#define size 6



int queue[6][2] = {0};

int top = -1;

int bottom;
//function to add the process in the priority queue
void push(int value, int pr)
{
	int i,j,k;

	if(top < size-1)

		{

			if(queue[top][1] < pr)

			{

				for(i=0;i<top;i++)

				{

					if(queue[i][1] < pr)

					{

						break;

					}

				}

			for(j=top;j>=i;j--)

			{

				queue[j+1][0] = queue[j][0];

				queue[j+1][1] = queue[j][1];

			}

			top++;

			queue[i][0] = value;

			queue[i][1] = pr;

			}

			else

			{

			top++;

			queue[top][0] = value;

			queue[top][1] = pr;

		}

	}

	else

	{

	printf("queue overflow \n");

	}

}
//function to delete process from the queue
int pop()

{

	int i;
	int temp;

	if(queue[0][0] == 0)

	{

		printf("\n The queue is empty  \n");

	}

	else

	{

		temp = queue[0][0];
		
		for(i=0;i<top;i++)

		{

			queue[i][0] = queue[i+1][0];

			queue[i][1] = queue[i+1][1];

		}

		queue[top][0] = 0;

		queue[top][1] = 0;

		top--;

	}

	return temp;
}
//function to display the queue
void display()

{ 
	int i,j;

	printf("Element\t\t\tPriority \n");

	for(i=size - 1;i>=0;i--)

	{

		for(j=0;j<2;j++)

		{

			printf(" %d\t",queue[i][j]);

		}

		printf("\n");

	}

}

int c_add=0, c_sub=0, c_mul=0;//initializing the global variables

/* There are 6 processes.Every mathematical function is being 
performed by two out of the six processes. The value of the 
answer of that mathematical operation would be of that of the
process which last accessed the function */
 
//function to perform the mathematical operations
void add(int a,int b)
{
	c_add = a + b;
}

void subtract(int a,int b)
{
	c_sub = a - b;
}

void multiply(int a,int b)
{
	c_mul = a * b;
}

void operation(int val)
{
	
	if(val==1804289383)
	{
		process1.priority--;		
		add(10,2);
	}
	if(val==846930886)
	{	
		process2.priority--;
		add(13,4);
	}	
	
	if(val==1681692777)
	{
		process3.priority--;
		subtract(21,4);
	}
	if(val==1714636915)
	{
		process4.priority--;
		subtract(17,1);
	}
	if(val==1957747793)
	{
		process5.priority--;
		multiply(3,2);
	}
	if(val==424238335)
	{
		process6.priority--;
		multiply(5,6);
	}


}

//generating the log file
void logfile()
{
	FILE *fptr;
	fptr=fopen("log3.txt","a");
	fprintf(fptr,"Addition answer: %d\n",c_add);
	fprintf(fptr,"Subtraction answer: %d\n",c_sub);
	fprintf(fptr,"Multiplication answer: %d\n",c_mul);
	fclose(fptr);
}


void main()
{
	//intializing the process id with the random integers generated by the function
	process1.pid = identifier();
	process2.pid = identifier();
	process3.pid = identifier();
	process4.pid = identifier();
	process5.pid = identifier();
	process6.pid = identifier();

	//giving the priority to the processes
	process1.priority = 12;
	process2.priority = 3;
	process3.priority = 7;
	process4.priority = 14;
	process5.priority = 1;
	process6.priority = 10;


	push(process1.pid,process1.priority);
	push(process2.pid,process2.priority);
	push(process3.pid,process3.priority);
	push(process4.pid,process4.priority);
	push(process5.pid,process5.priority);
	push(process6.pid,process6.priority);

	start = clock();
	double cpu_time_used;
	int delp;
	//printf("%d\n%d\n%d\n%d\n%d\n%d\n",process1.pid,process2.pid,process3.pid,process4.pid,process5.pid,process6.pid);
	while(queue[0][0]!=0)
	{
				
		operation(queue[0][0]);
		delp = pop();
		printf("\nDeleted process : %d",delp);

	}
	
	printf("\nAddition answer: %d\n",c_add);
	printf("Subtraction answer: %d\n",c_sub);
	printf("Multiplication answer: %d\n",c_mul);
	logfile();	

	end = clock();
	cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;
	printf("\nTime used %f",cpu_time_used);



}
